# Generated by Django 4.2.7 on 2023-11-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=25, unique=True)),
                ('pokeId', models.CharField(max_length=3)),
                ('weight', models.CharField(max_length=4)),
            ],
        ),
    ]
