# Generated by Django 4.2.7 on 2023-11-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_pokemon_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokeId',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.CharField(max_length=5),
        ),
    ]
